# 🧹 Limpieza de Datos en Datasets Mineros

## 🎯 Objetivos
- Identificar y corregir errores de tipos de datos
- Detectar y eliminar duplicados
- Tratar valores inválidos o fuera de rango
- Limpiar datos categóricos (formato, errores tipográficos)

---

## 🧪 Paso 1: Cargar e Inspeccionar el Dataset Minero sin Limpiar

Ejecutá la celda para crear el dataset sintético y observá los problemas que tiene (tipos mezclados, valores raros, inconsistencias en mayúsculas, etc.)

**Ejercicios de las celdas vacías:**
- Calculá el **total de producción diaria** (`Daily_Production (tonnes)`)
- Calculá el **total de grado de mineral** (`Ore_Grade (%)`)

> ⚠️ ¿Podés hacerlo sin limpiar antes? ¿Qué pasa?

In [1]:
import pandas as pd
import numpy as np

# Creamos un dataset minero sintético con varios problemas comunes de calidad de datos
data = {
    'Mine_ID': ['MN001', 'MN002', 'MN002', 'mn003', 'MN004', 'MN005', 'MN006', 'MN007', None, 'MN004', 'MN004'],
    'Mineral': ['Gold', 'silver', 'Silver', 'gold', 'Gold', 'copper', 'copper', 'Lithium ', 'Lithium', 'GOLD', 'Gold'],
    'Ore_Grade (%)': ['1.5', '0.8', '0.8', '2.0', '999', '1.2', 'NaN', '0.6', '0.6', '999', '999'],
    'Daily_Production (tonnes)': ["1000", 850, 850, 1200, 3000, '500', 750, 800, 800, 3000, 3000]
}

df = pd.DataFrame(data)

# Mostramos los datos sin procesar
df

   Mine_ID   Mineral Ore_Grade (%) Daily_Production (tonnes)
0    MN001      Gold           1.5                      1000
1    MN002    silver           0.8                       850
2    MN002    Silver           0.8                       850
3    mn003      gold           2.0                      1200
4    MN004      Gold           999                      3000
5    MN005    copper           1.2                       500
6    MN006    copper           NaN                       750
7    MN007  Lithium            0.6                       800
8     None   Lithium           0.6                       800
9    MN004      GOLD           999                      3000
10   MN004      Gold           999                      3000

In [3]:
# Total Daily_Production (tonnes)
df['Daily_Production (tonnes)'].sum()

TypeError: can only concatenate str (not "int") to str

In [4]:
# Total Ore_Grade (%)
df['Ore_Grade (%)'].sum()

'1.50.80.82.09991.2NaN0.60.6999999'

## 🔄 Paso 2: Problemas de Tipos de Datos

- Revisá los tipos de datos actuales con `.dtypes`
- Convertí las columnas numéricas al tipo correcto (los valores están almacenados como texto)

---

In [7]:
# Checkeamos los tipos
print(df.dtypes)

Mine_ID                      object
Mineral                      object
Ore_Grade (%)                object
Daily_Production (tonnes)     int64
dtype: object

np.int64(15750)

In [10]:
# Convertimos la columna a numérica.
# errors='coerce' transforma cualquier valor no convertible (ej: texto, 'NaN') en NaN,
# en lugar de lanzar un error. Así podemos operar la columna sin interrupciones.
df['Daily_Production (tonnes)'] = pd.to_numeric(df['Daily_Production (tonnes)'], errors='coerce')

df['Daily_Production (tonnes)'].sum()

np.int64(15750)

In [9]:
df['Ore_Grade (%)'] = pd.to_numeric(df['Ore_Grade (%)'], errors='coerce')
df['Ore_Grade (%)'].sum()

np.float64(3004.5)

In [11]:
print(df.dtypes)

Mine_ID                       object
Mineral                       object
Ore_Grade (%)                float64
Daily_Production (tonnes)      int64
dtype: object

In [12]:
df

   Mine_ID   Mineral  Ore_Grade (%)  Daily_Production (tonnes)
0    MN001      Gold            1.5                       1000
1    MN002    silver            0.8                        850
2    MN002    Silver            0.8                        850
3    mn003      gold            2.0                       1200
4    MN004      Gold          999.0                       3000
5    MN005    copper            1.2                        500
6    MN006    copper            NaN                        750
7    MN007  Lithium             0.6                        800
8     None   Lithium            0.6                        800
9    MN004      GOLD          999.0                       3000
10   MN004      Gold          999.0                       3000

## 🧬 Paso 3: Manejar Duplicados y Datos Faltantes

- Eliminá filas duplicadas
- Identificá cuántos valores nulos hay por columna
- Eliminá filas donde falten datos críticos (`Mine_ID` u `Ore_Grade`)

---

In [14]:
# Eliminamos filas duplicadas
df = df.drop_duplicates()

# Mostramos los valores faltantes por columna
print("Valores faltantes por columna:")
print(df.isnull().sum())

# Eliminamos filas con campos críticos vacíos
df = df.dropna(subset=['Mine_ID', 'Ore_Grade (%)'])

df

Valores faltantes por columna:
Mine_ID                      0
Mineral                      0
Ore_Grade (%)                0
Daily_Production (tonnes)    0
dtype: int64

  Mine_ID   Mineral  Ore_Grade (%)  Daily_Production (tonnes)
0   MN001      Gold            1.5                       1000
1   MN002    silver            0.8                        850
2   MN002    Silver            0.8                        850
3   mn003      gold            2.0                       1200
4   MN004      Gold          999.0                       3000
5   MN005    copper            1.2                        500
7   MN007  Lithium             0.6                        800
9   MN004      GOLD          999.0                       3000

## 🏷️ Paso 4: Estandarizar Datos Categóricos

- Normalizá `Mine_ID` → todo en mayúsculas, sin espacios
- Normalizá `Mineral` → primera letra en mayúscula, sin espacios extra
- Verificá los valores únicos resultantes con `.unique()`

---

In [15]:
# Limpiamos Mine_ID (convertimos a mayúsculas y eliminamos espacios al inicio/final)
df['Mine_ID'] = df['Mine_ID'].str.upper().str.strip()

# Limpiamos la columna Mineral (primera letra en mayúscula, sin espacios extra)
df['Mineral'] = df['Mineral'].str.lower().str.strip().str.capitalize()

# Verificamos los valores únicos resultantes
print("Minerales luego de la limpieza:")
print(df['Mineral'].unique())

Minerales luego de la limpieza:
['Gold' 'Silver' 'Copper' 'Lithium']

In [16]:
df

  Mine_ID  Mineral  Ore_Grade (%)  Daily_Production (tonnes)
0   MN001     Gold            1.5                       1000
1   MN002   Silver            0.8                        850
2   MN002   Silver            0.8                        850
3   MN003     Gold            2.0                       1200
4   MN004     Gold          999.0                       3000
5   MN005   Copper            1.2                        500
7   MN007  Lithium            0.6                        800
9   MN004     Gold          999.0                       3000

## ⚠️ Paso 5: Manejar Outliers y Valores Fuera de Rango

- Filtrá los valores de `Ore_Grade (%)` que sean realistas (rango válido: **0% a 10%**)
- Mostrá el dataset resultante

---

In [17]:
# Para este dataset, asumimos un rango realista de Ore_Grade entre 0% y 10%
df = df[(df['Ore_Grade (%)'] >= 0) & (df['Ore_Grade (%)'] <= 10)]

# Mostramos los datos limpios
df.reset_index(drop=True, inplace=True)
df

  Mine_ID  Mineral  Ore_Grade (%)  Daily_Production (tonnes)
0   MN001     Gold            1.5                       1000
1   MN002   Silver            0.8                        850
2   MN002   Silver            0.8                        850
3   MN003     Gold            2.0                       1200
4   MN005   Copper            1.2                        500
5   MN007  Lithium            0.6                        800

## ✅ Dataset Final Limpio

- Eliminá cualquier duplicado restante
- Mostrá el resultado final listo para análisis

In [18]:
df = df.drop_duplicates()
df

  Mine_ID  Mineral  Ore_Grade (%)  Daily_Production (tonnes)
0   MN001     Gold            1.5                       1000
1   MN002   Silver            0.8                        850
3   MN003     Gold            2.0                       1200
4   MN005   Copper            1.2                        500
5   MN007  Lithium            0.6                        800