# 🧪 Integrated Practical Notebook: Python Data Structures and Data Preprocessing

This notebook merges the practical content from the previous sessions into a single workflow.  
The objective is to help students move from **basic Python data structures** to **data preprocessing tasks** commonly used in data science projects, ending with **outlier detection and removal**.

## Learning goals

By the end of this notebook, you should be able to:

1. use **lists** for simple data storage and inspection  
2. use **NumPy arrays** for numerical operations  
3. create and manipulate **pandas DataFrames**  
4. clean simple text inconsistencies and duplicates  
5. inspect and treat **missing values**  
6. detect and remove **outliers** using the **IQR method**

> Complete the cells marked with **TODO**.  
> Focus on understanding the workflow, not just producing the final output.

## 1. Python lists: simple data storage

Lists are useful for storing ordered values and doing quick exploratory calculations.
In this mining example, you are given daily gold prices.

In [1]:
# Precios diarios del oro en USD/oz
gold_prices = [1930.5, 1942.3, 1928.4, 1950.0, 1935.6, 1962.1, 1948.7]

# TODO 1: mostramos el numero de observaciones
print("Numero de observaciones: ", len(gold_prices))

# TODO 2: calculamos la media o promedio
average_price = sum(gold_prices) / len(gold_prices)
print("Media o promedio:", average_price)

# TODO 3: agregamos nuevo valor: 1955.3
gold_prices.append(1955.3)
print("Lista con nuevo precio:", gold_prices)

# TODO 4: ordenamos lista
gold_prices.sort()
print("Lista ordenada:", gold_prices)

# TODO 5: imprimimos el valor minimo y maximo
print("Mayor: ", max(gold_prices))
print("Menor: ", min(gold_prices))

gold_prices

Numero de observaciones:  7
Media o promedio: 1942.5142857142857
Lista con nuevo precio: [1930.5, 1942.3, 1928.4, 1950.0, 1935.6, 1962.1, 1948.7, 1955.3]
Lista ordenada: [1928.4, 1930.5, 1935.6, 1942.3, 1948.7, 1950.0, 1955.3, 1962.1]
Mayor:  1962.1
Menor:  1928.4

[1928.4, 1930.5, 1935.6, 1942.3, 1948.7, 1950.0, 1955.3, 1962.1]

## 2. NumPy arrays: numerical computation

Arrays are more efficient than lists for numerical workflows.  
Here you have ore grade data from three pits.

In [2]:
import numpy as np

# Leyes de mineral de 3 tajos
grades = np.array([
    [0.80, 1.00, 0.90, 1.10, 0.85],   # Tajo A
    [1.20, 1.00, 1.30, 1.10, 1.15],   # Tajo B
    [0.70, 0.65, 0.80, 0.75, 0.72]    # Tajo C
])

# TODO 1: calculamos el promedio de ley por tajo
print("Promedio por tajo:", np.mean(grades, axis=1))

# TODO 2: calculamos el promedio general de todas las leyes
print("Promedio general:", np.mean(grades))

# TODO 3: mostramos la ley minima y maxima
print("Ley minima:", np.min(grades))
print("Ley maxima:", np.max(grades))

# TODO 4: aplicamos una corrección de laboratorio de +0.05 a todos los valores
corrected_grades = grades + 0.05
print("Leyes corregidas:\n", corrected_grades)

grades

Promedio por tajo: [0.93  1.15  0.724]
Promedio general: 0.9346666666666666
Ley minima: 0.65
Ley maxima: 1.3
Leyes corregidas:
 [[0.85 1.05 0.95 1.15 0.9 ]
 [1.25 1.05 1.35 1.15 1.2 ]
 [0.75 0.7  0.85 0.8  0.77]]

array([[0.8 , 1.  , 0.9 , 1.1 , 0.85],
       [1.2 , 1.  , 1.3 , 1.1 , 1.15],
       [0.7 , 0.65, 0.8 , 0.75, 0.72]])

## 3. pandas DataFrame: tabular data

DataFrames are the workhorse of data science.  
This example contains daily production information for several mining operations.

In [3]:
import pandas as pd

data = {
    "Mine": ["Cerro Azul", "El Dorado", "Zinc Valley", "Copper Hill", "Lithium Lakes"],
    "Mineral": ["Gold", "Gold", "Zinc", "Copper", "Lithium"],
    "Daily_Production_t": [1200, 1350, 800, 950, 700],
    "Ore_Grade_pct": [1.2, 1.1, 4.5, 2.3, 0.7]
}

df = pd.DataFrame(data)

# TODO 1: inspeccionamos el dataset
print(df.head())
print(df.describe())

# TODO 2: creamos una nueva columna llamada Metal_Content_kg
# Fórmula: produccion_t * ley_pct * 10
df["Metal_Content_kg"] = df["Daily_Production_t"] * df["Ore_Grade_pct"] * 10
print(df)

# TODO 3: filtramos filas con Ore_Grade_pct > 1.0
high_grade_df = df[df["Ore_Grade_pct"] > 1.0]
print(high_grade_df)

# TODO 4: calculamos el promedio de produccion diaria por mineral
grouped = df.groupby("Mineral")["Daily_Production_t"].mean()
print(grouped)

df

            Mine  Mineral  Daily_Production_t  Ore_Grade_pct
0     Cerro Azul     Gold                1200            1.2
1      El Dorado     Gold                1350            1.1
2    Zinc Valley     Zinc                 800            4.5
3    Copper Hill   Copper                 950            2.3
4  Lithium Lakes  Lithium                 700            0.7
       Daily_Production_t  Ore_Grade_pct
count            5.000000       5.000000
mean          1000.000000       1.960000
std            271.569512       1.538831
min            700.000000       0.700000
25%            800.000000       1.100000
50%            950.000000       1.200000
75%           1200.000000       2.300000
max           1350.000000       4.500000
            Mine  Mineral  Daily_Production_t  Ore_Grade_pct  Metal_Content_kg
0     Cerro Azul     Gold                1200            1.2           14400.0
1      El Dorado     Gold                1350            1.1           14850.0
2    Zinc Valley     Zinc                 800            4.5           36000.0
3    Copper Hill   Copper                 950            2.3           21850.0
4  Lithium Lakes  Lithium                 700            0.7            4900.0
          Mine Mineral  Daily_Production_t  Ore_Grade_pct  Metal_Content_kg
0   Cerro Azul    Gold                1200            1.2           14400.0
1    El Dorado    Gold                1350            1.1           14850.0
2  Zinc Valley    Zinc                 800            4.5           36000.0
3  Copper Hill  Copper                 950            2.3           21850.0
Mineral
Copper      950.0
Gold       1275.0
Lithium     700.0
Zinc        800.0
Name: Daily_Production_t, dtype: float64

            Mine  Mineral  Daily_Production_t  Ore_Grade_pct  Metal_Content_kg
0     Cerro Azul     Gold                1200            1.2           14400.0
1      El Dorado     Gold                1350            1.1           14850.0
2    Zinc Valley     Zinc                 800            4.5           36000.0
3    Copper Hill   Copper                 950            2.3           21850.0
4  Lithium Lakes  Lithium                 700            0.7            4900.0

## 4. Basic data cleaning: duplicates, text uniformity, and missing production

Before advanced preprocessing, it is useful to clean obvious issues:
- duplicated rows
- inconsistent text labels
- missing values in a single column

In [5]:
import pandas as pd

messy_data = {
    "Mine_ID": ["mn001", "MN001", "MN002", "MN002", " MN003 "],
    "Mineral": ["gold", "Gold ", "Copper", "copper", " Silver"],
    "Production": [1000, 1000, 850, 850, None]
}

df_messy = pd.DataFrame(messy_data)

# TODO 1: inspeccionamos el dataset original
print(df_messy)

# TODO 2: estandarizamos el texto (mayusculas y espacios)
df_clean = df_messy.copy()
df_clean["Mine_ID"] = df_clean["Mine_ID"].str.strip().str.upper()
df_clean["Mineral"] = df_clean["Mineral"].str.strip().str.capitalize()

# TODO 3: eliminamos duplicados luego de limpiar el texto
df_clean = df_clean.drop_duplicates()

# TODO 4: rellenamos valores faltantes de Production con 0
df_clean["Production"] = df_clean["Production"].fillna(df_clean["Production"].median())

# TODO 5: inspeccionamos el resultado limpio
print(df_clean)

df_messy

   Mine_ID  Mineral  Production
0    mn001     gold      1000.0
1    MN001    Gold       1000.0
2    MN002   Copper       850.0
3    MN002   copper       850.0
4   MN003    Silver         NaN
  Mine_ID Mineral  Production
0   MN001    Gold      1000.0
2   MN002  Copper       850.0
4   MN003  Silver       925.0

   Mine_ID  Mineral  Production
0    mn001     gold      1000.0
1    MN001    Gold       1000.0
2    MN002   Copper       850.0
3    MN002   copper       850.0
4   MN003    Silver         NaN

## 5. Missing values in a production dataset

Now we move into formal preprocessing.  
Some records are incomplete due to sensor failures or manual entry problems.

### Tasks
1. inspect the data  
2. count missing values  
3. apply reasonable imputations  
4. verify the result

In [9]:
import pandas as pd
import numpy as np

production_data = {
    "Date": pd.date_range("2026-02-01", periods=10, freq="D"),
    "Plant": ["North", "North", None, "South", "South", "East", "East", None, "North", "South"],
    "Ore_Tonnage_t": [1250, 1320, 1285, 1405, 1370, 1190, 1215, 1300, 1340, 1385],
    "Recovery_pct": [88.2, np.nan, 87.5, 91.0, np.nan, 86.8, 87.1, 89.4, 90.1, np.nan],
    "Energy_kWh": [5200, 5400, np.nan, 6100, 5900, 5000, np.nan, 5600, 5750, 6050],
    "Operator_Shift": ["A", "B", "A", None, "C", "A", "B", "B", None, "C"]
}

df_prod = pd.DataFrame(production_data)

# TODO 1: inspeccionamos el dataset
print(df_prod.head())
print(df_prod.dtypes)
print(df.info())

# TODO 2: contamos los valores faltantes por columna
missing_counts = df_prod.isna().sum()
print("Cantidad de nulos")
print(missing_counts)

# TODO 3: imputamos los valores faltantes
# Texto: rellenamos con el valor mas frecuente (moda)
df_prod["Plant"] = df_prod["Plant"].fillna(df_prod["Plant"].mode()[0])
df_prod["Operator_Shift"] = df_prod["Operator_Shift"].fillna(df_prod["Operator_Shift"].mode()[0])

# Numericos: rellenamos con la media de cada columna
df_prod["Recovery_pct"] = df_prod["Recovery_pct"].fillna(df_prod["Recovery_pct"].mean())
df_prod["Energy_kWh"] = df_prod["Energy_kWh"].fillna(df_prod["Energy_kWh"].mean())

# TODO 4: verificamos que no queden valores faltantes
print(df_prod.isna().sum())

df_prod

        Date  Plant  Ore_Tonnage_t  Recovery_pct  Energy_kWh Operator_Shift
0 2026-02-01  North           1250          88.2      5200.0              A
1 2026-02-02  North           1320           NaN      5400.0              B
2 2026-02-03    NaN           1285          87.5         NaN              A
3 2026-02-04  South           1405          91.0      6100.0            NaN
4 2026-02-05  South           1370           NaN      5900.0              C
Date              datetime64[us]
Plant                        str
Ore_Tonnage_t              int64
Recovery_pct             float64
Energy_kWh               float64
Operator_Shift               str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Mine                5 non-null      str
 1   Mineral             5 non-null      str
 2   Daily_Production_t  5 non-null      int64
 3   Ore_Grade_pct       5 non-null      float64
 4   Metal_Content_kg    5 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 332.0 bytes
None
Cantidad de nulos
Date              0
Plant             2
Ore_Tonnage_t     0
Recovery_pct      3
Energy_kWh        2
Operator_Shift    2
dtype: int64
Date              0
Plant             0
Ore_Tonnage_t     0
Recovery_pct      0
Energy_kWh        0
Operator_Shift    0
dtype: int64

        Date  Plant  Ore_Tonnage_t  Recovery_pct  Energy_kWh Operator_Shift
0 2026-02-01  North           1250     88.200000      5200.0              A
1 2026-02-02  North           1320     88.585714      5400.0              B
2 2026-02-03  North           1285     87.500000      5625.0              A
3 2026-02-04  South           1405     91.000000      6100.0              A
4 2026-02-05  South           1370     88.585714      5900.0              C
5 2026-02-06   East           1190     86.800000      5000.0              A
6 2026-02-07   East           1215     87.100000      5625.0              B
7 2026-02-08  North           1300     89.400000      5600.0              B
8 2026-02-09  North           1340     90.100000      5750.0              A
9 2026-02-10  South           1385     88.585714      6050.0              C

## 6. Outlier detection and removal with IQR

This is the last topic for this session.  
The dataset below contains drillhole gold assays. One value looks suspiciously high.

### Tasks
1. compute Q1, Q3 and IQR for `Au_gpt`  
2. calculate lower and upper bounds  
3. identify the outlier rows  
4. remove outliers  
5. compare the mean before and after filtering

In [10]:
import pandas as pd

assay_data = {
    "Hole_ID": ["DH001", "DH002", "DH003", "DH004", "DH005", "DH006", "DH007", "DH008"],
    "Au_gpt": [1.2, 1.5, 1.4, 1.6, 1.3, 1.5, 1.4, 12.8],
    "Cu_pct": [0.22, 0.25, 0.24, 0.27, 0.23, 0.26, 0.24, 0.29]
}

df_assay = pd.DataFrame(assay_data)

# TODO 1: calculamos los cuartiles y el RIC (Rango Intercuartílico) para Au_gpt
Q1 = df_assay["Au_gpt"].quantile(0.25)
Q3 = df_assay["Au_gpt"].quantile(0.75)
IQR = Q3 - Q1
print(f"Q1: {Q1} | Q3: {Q3} | IQR: {IQR}")

# TODO 2: calculamos los limites inferior y superior
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f"Limite inferior: {lower_bound} | Limite superior: {upper_bound}")

# TODO 3: identificamos los outliers
outliers = df_assay[(df_assay["Au_gpt"] < lower_bound) | (df_assay["Au_gpt"] > upper_bound)]
print("Outliers:")
print(outliers)

# TODO 4: eliminamos los outliers
df_assay_clean = df_assay[(df_assay["Au_gpt"] >= lower_bound) & (df_assay["Au_gpt"] <= upper_bound)]

# TODO 5: comparamos las medias antes y despues del filtrado
print("Media antes del filtrado:", df_assay["Au_gpt"].mean())
print("Media despues del filtrado:", df_assay_clean["Au_gpt"].mean())

df_assay

Q1: 1.375 | Q3: 1.525 | IQR: 0.1499999999999999
Limite inferior: 1.1500000000000001 | Limite superior: 1.7499999999999998
Outliers:
  Hole_ID  Au_gpt  Cu_pct
7   DH008    12.8    0.29
Media antes del filtrado: 2.8375
Media despues del filtrado: 1.4142857142857144

  Hole_ID  Au_gpt  Cu_pct
0   DH001     1.2    0.22
1   DH002     1.5    0.25
2   DH003     1.4    0.24
3   DH004     1.6    0.27
4   DH005     1.3    0.23
5   DH006     1.5    0.26
6   DH007     1.4    0.24
7   DH008    12.8    0.29